MonitorShop.Web/Models/Monitor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Linq;
using System.Security.Policy;
using System.Web;

namespace MonitorShop.Web.Models
{
    // 
    public class Monitor
    {
        [Display(Name = "Monitor ID")]
        [Required]
        public int ID { get; set; }

        [Display(Name = "Brand ID")]
        [Required]
        public int BrandID { get; set; }

        [Display(Name = "Monitor Diagonal")]
        [Required]
        public double Diagonal { get; set; }

        [Display(Name = "Monitor Screen Ratio")]
        [Required]
        public string Ratio { get; set; }

        [Display(Name = "Monitor Resolution")]
        [Required]
        [StringLength(5, MinimumLength = 3)]
        public string Resolution { get; set; }

        [Display(Name = "Monitor Refresh Rate")]
        [Required]
        public int RefreshRate { get; set; }

        [Display(Name = "Monitor Response Time")]
        [Required]
        public int ResponseTime { get; set; }

        [Display(Name = "Monitor Curved")]
        [Required]
        public bool Curved { get; set; }

        [Display(Name = "Monitor Price")]
        [Required]
        public int Price { get; set; }
    }
}

MonitorShop.Web/Models/MonitorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MonitorShop.Web.Models
{
    public class MonitorViewModel
    {
        public Monitor EditedMonitor { get; set; }
        public List<Monitor> ListOfMonitors { get; set; }
    }
}

MonitorShop.Web/Controllers/MonitorsController.cs
using AutoMapper;
using MonitorShop.Logic;
using MonitorShop.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MonitorShop.Data;
using MonitorShop.Repository;
using System.ComponentModel.DataAnnotations;

namespace MonitorShop.Web.Controllers
{
    public class MonitorsController : Controller
    {
        IMonitorLogic logic;
        IMapper mapper;
        MonitorViewModel vm;
        
        public MonitorsController()
        {
            MonitorDatabaseEntities db = new MonitorDatabaseEntities();
            MonitorRepo monitorRepo = new MonitorRepo(db);
            MonitorbrandRepo brandRepo = new MonitorbrandRepo(db);
            RaktarinfoRepo infoRepo = new RaktarinfoRepo(db);

            logic = new MonitorLogic(monitorRepo, brandRepo, infoRepo);
            mapper = MapperFacotry.CreateMapper();
            vm = new MonitorViewModel();

            vm.EditedMonitor = new Monitor();
            var monitors = logic.GetAllMonitorItems();
            vm.ListOfMonitors = mapper.Map<IEnumerable<Data.MONITOR>, List<Models.Monitor>>(monitors);
        }

        private Monitor GetMonitorModel(int id)
        {
            MONITOR monitor = logic.GetMonitorItemById(id);
            return mapper.Map<Data.MONITOR, Models.Monitor>(monitor);
        }

        // GET: Monitors
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("MonitorIndex", vm);
        }

        // GET: Monitors/Details/5
        public ActionResult Details(int id)
        {
            return View("MonitorDetails", GetMonitorModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete OK";
            try
            {
                logic.DeleteMonitor(id);
            }
            catch (Exception)
            {
                TempData["editResult"] = "Delete FAIL";
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedMonitor = GetMonitorModel(id);
            return View("MonitorIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Monitor monitor, string editAction)
        {
            if (ModelState.IsValid && monitor != null)
            {
                TempData["editResult"] = "Edit OK";

                if (editAction == "AddNew")
                {
                    try
                    {
                        this.logic.AddMonitor(monitor.ID, monitor.BrandID, monitor.Diagonal, monitor.Ratio,
                        monitor.Resolution, monitor.RefreshRate, monitor.ResponseTime, monitor.Curved, monitor.Price);
                    }
                        catch (Exception)
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
            }
                else
                {
                    try
                    {
                        this.logic.ChangeMonitor(monitor.ID, monitor.Diagonal, monitor.Ratio,
                            monitor.Resolution, monitor.RefreshRate, monitor.ResponseTime, monitor.Curved, monitor.Price);
                    }
                    catch (Exception)
                    {
                        TempData["editResult"] = "Edit FAIL";
                    }
                }
                return RedirectToAction(nameof(Index));

            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedMonitor = monitor;
                return View("MonitorIndex", vm);
            }
        }

    }
}

MonitorShop.Web/Views/Monitors/MonitorDetails.cshtml
@model MonitorShop.Web.Models.Monitor
@{
    ViewBag.Title = "MonitorDetails";
}

<h2>MonitorDetails</h2>

<h2>Datasheet of one monitor</h2>

<!-- 
<a href="/Monitors/Index">Back to the List</a>
    -->


<table border="1">
    <tr>
        <td>The ID for the MONITOR</td>
        <td>@Model.ID</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.BrandID)</td>
        <td>@Html.DisplayFor(m=>m.BrandID)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.Diagonal)</td>
        <td>@Html.DisplayFor(m=>m.Diagonal)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.Ratio)</td>
        <td>@Html.DisplayFor(m=>m.Ratio)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.Resolution)</td>
        <td>@Html.DisplayFor(m=>m.Resolution)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.RefreshRate)</td>
        <td>@Html.DisplayFor(m=>m.RefreshRate)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.Curved)</td>
        <td>@Html.DisplayFor(m=>m.Curved)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.Price)</td>
        <td>@Html.DisplayFor(m=>m.Price)</td>
    </tr>

</table>

MonitorShop.Web/Views/Monitors/MonitorEdit.cshtml
@model MonitorShop.Web.Models.Monitor

<h2>Edit one Monitor</h2>

@using (Html.BeginForm("Edit", "Monitors"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m=>m.BrandID)</div>
    <div class="editor-field">@Html.EditorFor(m=>m.BrandID)</div>

    <div class="editor-label">@Html.LabelFor(m=>m.Diagonal)</div>
    <div class="editor-field">@Html.EditorFor(m=>m.Diagonal)</div>

    <div class="editor-label">@Html.LabelFor(m=>m.Ratio)</div>
    <div class="editor-field">@Html.EditorFor(m=>m.Ratio)</div>

    <div class="editor-label">@Html.LabelFor(m=>m.Resolution)</div>
    <div class="editor-field">@Html.EditorFor(m=>m.Resolution)</div>

    <div class="editor-label">@Html.LabelFor(m=>m.RefreshRate)</div>
    <div class="editor-field">@Html.EditorFor(m=>m.RefreshRate)</div>

    <div class="editor-label">@Html.LabelFor(m=>m.Curved)</div>
    <div class="editor-field">@Html.EditorFor(m=>m.Curved)</div>

    <div class="editor-label">@Html.LabelFor(m=>m.Price)</div>
    <div class="editor-field">@Html.EditorFor(m=>m.Price)</div>

    <input type="submit" value="SEND" />

}

MonitorShop.Web/Views/Monitors/MonitorIndex.cshtml
@model MonitorShop.Web.Models.MonitorViewModel
@{
    ViewBag.Title = "MonitorIndex";
}

<h2>Monitor Index</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("MonitorEdit", Model.EditedMonitor)

@Html.Partial("MonitorList", Model.ListOfMonitors)

MonitorShop.Web/Views/Monitors/MonitorList.cshtml
@model IEnumerable<MonitorShop.Web.Models.Monitor>

<h2>List of Monitors</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m=>m.First().BrandID)</th>
            <th>@Html.DisplayNameFor(m => m.First().ID)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>

        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m=>item.BrandID) </td>
                <td>@Html.DisplayFor(m=>item.ID) </td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.ID })</td>
                <td>@Html.ActionLink("[SHOW]", "Remove", new { id = item.ID })</td>
                <td>@Html.ActionLink("[SHOW]", "Edit", new { id = item.ID })</td>                
            </tr>
        }
    </table>
}